import type { GalleryPhoto } from '@/lib/gallery-types'

export const STATIC_GALLERY_PHOTOS: GalleryPhoto[] = [
  { desktop: '/events2_1200.webp', mobile: '/events2_800.webp', alt: 'Events am Abend', tag: 'Events', ratio: 'wide' },
  { desktop: '/firmen_1200.webp', mobile: '/firmen_800.webp', alt: 'Firmenveranstaltungen', tag: 'Business', ratio: 'wide' },
  { desktop: '/events3_1200.webp', mobile: '/events3_800.webp', alt: 'Tanz und Musik Event', tag: 'Tanz', ratio: 'wide' },
  { desktop: '/hochzeit_restaurant_desktop_1600x1200.webp', mobile: '/hochzeit_restaurant_mobile_800x600.webp', alt: 'Hochzeit im Restaurant', tag: 'Hochzeit', ratio: 'wide' },
  { desktop: '/banket.webp', mobile: '/banket.webp', alt: 'Bankettsaal', tag: 'Saal', ratio: 'square' },
  { desktop: '/momente_1200.webp', mobile: '/momente_800.webp', alt: 'Atmosphäre im Restaurant', tag: 'Atmosphäre', ratio: 'tall' },
  { desktop: '/kulinarik_1600.webp', mobile: '/kulinarik_1200.webp', alt: 'Fine Dining Teller', tag: 'Kulinarik', ratio: 'tall' },
  { desktop: '/terrace_1200.webp', mobile: '/terrace_800.webp', alt: 'Terrasse', tag: 'Terrasse', ratio: 'wide' },
  { desktop: '/german_food_1200.webp', mobile: '/german_food_800.webp', alt: 'Gericht der Küche', tag: 'Küche', ratio: 'tall' },
  { desktop: '/german_food2_1200.webp', mobile: '/german_food2_800.webp', alt: 'Spezialität des Hauses', tag: 'Küche', ratio: 'wide' },
  { desktop: '/menu-media/soljanka-1024.webp', mobile: '/menu-media/soljanka-640.webp', alt: 'Vorspeise Suppe', tag: 'Vorspeise', ratio: 'square' },
  { desktop: '/menu-media/wuerzfleisch-1024.webp', mobile: '/menu-media/wuerzfleisch-640.webp', alt: 'Würzfleisch', tag: 'Klassiker', ratio: 'square' },
  { desktop: '/menu-media/schweineschnitzel-1024.webp', mobile: '/menu-media/schweineschnitzel-640.webp', alt: 'Schnitzel', tag: 'Klassiker', ratio: 'tall' },
  { desktop: '/menu-media/zigeuner-schnitzel-1024.webp', mobile: '/menu-media/zigeuner-schnitzel-640.webp', alt: 'Schnitzelgericht', tag: 'Küche', ratio: 'wide' },
  { desktop: '/menu-media/schnitzel-au-four-1024.webp', mobile: '/menu-media/schnitzel-au-four-640.webp', alt: 'Schnitzel au four', tag: 'Küche', ratio: 'tall' },
  { desktop: '/menu-media/alt-nebraer-hacksteak-1024.webp', mobile: '/menu-media/alt-nebraer-hacksteak-640.webp', alt: 'Hacksteak', tag: 'Küche', ratio: 'square' },
  { desktop: '/menu-media/pfannenschaschlik-1024.webp', mobile: '/menu-media/pfannenschaschlik-640.webp', alt: 'Pfannenschaschlik', tag: 'Küche', ratio: 'tall' },
  { desktop: '/menu-media/schuesselsuelze-1024.webp', mobile: '/menu-media/schuesselsuelze-640.webp', alt: 'Schüsselsülze', tag: 'Klassiker', ratio: 'wide' },
  { desktop: '/menu-media/currywurst-1024.webp', mobile: '/menu-media/currywurst-640.webp', alt: 'Currywurst', tag: 'Klassiker', ratio: 'square' },
  { desktop: '/menu-media/burger-st-georg-1024.webp', mobile: '/menu-media/burger-st-georg-640.webp', alt: 'Burger St. Georg', tag: 'Burger', ratio: 'wide' },
  { desktop: '/menu-media/backfisch-1024.webp', mobile: '/menu-media/backfisch-640.webp', alt: 'Backfisch', tag: 'Klassiker', ratio: 'tall' },
  { desktop: '/menu-media/geschnetzeltes-1024.webp', mobile: '/menu-media/geschnetzeltes-640.webp', alt: 'Geschnetzeltes', tag: 'Küche', ratio: 'tall' },
  { desktop: '/menu-media/nebraer-biersteak-1024.webp', mobile: '/menu-media/nebraer-biersteak-640.webp', alt: 'Nebraer Biersteak', tag: 'Steak', ratio: 'wide' },
  { desktop: '/menu-media/schweinemedaillons-1024.webp', mobile: '/menu-media/schweinemedaillons-640.webp', alt: 'Schweinemedaillons', tag: 'Steak', ratio: 'wide' },
  { desktop: '/menu-media/zigeuner-steak-1024.webp', mobile: '/menu-media/zigeuner-steak-640.webp', alt: 'Zigeuner-Steak', tag: 'Steak', ratio: 'square' },
  { desktop: '/menu-media/bauernfruehstueck-1024.webp', mobile: '/menu-media/bauernfruehstueck-640.webp', alt: 'Bauernfrühstück', tag: 'Klassiker', ratio: 'wide' },
  { desktop: '/menu-media/strammer-max-1024.webp', mobile: '/menu-media/strammer-max-640.webp', alt: 'Strammer Max', tag: 'Klassiker', ratio: 'square' },
  { desktop: '/german_snacks_desktop.webp', mobile: '/german_snacks_mobile.webp', alt: 'Snacks zum Bier', tag: 'Snacks', ratio: 'tall' },
  { desktop: '/kostritzer_desktop.webp', mobile: '/kostritzer_mobile.webp', alt: 'Bier und Drinks', tag: 'Drinks', ratio: 'tall' },
]
