import type { MenuCategory, MenuDish } from '@/lib/menu-types'

export const MENU_PLACEHOLDER_DESKTOP = '/cafe_interior_1600x1200_optimized.webp'
export const MENU_PLACEHOLDER_MOBILE = '/cafe_interior_800x600_optimized.webp'

export const STATIC_MENU_CATEGORIES: MenuCategory[] = [
  { key: 'vorspeisen', de: 'Vorspeisen', en: 'Starters' },
  { key: 'hauptgerichte', de: 'Hauptgerichte', en: 'Main Courses' },
  { key: 'klassiker', de: 'Klassiker', en: 'Classics' },
  { key: 'pfanne-burger', de: 'Pfanne & Burger', en: 'Skillet & Burger' },
  { key: 'steaks-medaillons', de: 'Steaks & Medaillons', en: 'Steaks & Medallions' },
  { key: 'zum-bier', de: 'Zum Bier', en: 'For Beer' },
  { key: 'bier-drinks', de: 'Bier & Drinks', en: 'Beer & Drinks' },
]

export const STATIC_MENU_DISHES: MenuDish[] = [
  {
    id: 'soljanka',
    imgDesktop: '/menu-media/soljanka-1024.webp',
    imgMobile: '/menu-media/soljanka-640.webp',
    video: '/menu-media/soljanka.webm',
    tagDe: 'Vorspeise',
    tagEn: 'Starter',
    nameDe: 'Soljanka nach Art des Hauses',
    nameEn: 'House-Style Solyanka',
    descDe: 'Serviert mit Brot.',
    descEn: 'Served with bread.',
    price: '7,50€',
    category: 'vorspeisen',
  },
  {
    id: 'wuerzfleisch',
    imgDesktop: '/menu-media/wuerzfleisch-1024.webp',
    imgMobile: '/menu-media/wuerzfleisch-640.webp',
    video: '/menu-media/wuerzfleisch.webm',
    tagDe: 'Vorspeise',
    tagEn: 'Starter',
    nameDe: 'Würzfleisch',
    nameEn: 'Wuerzfleisch',
    descDe: 'Ragout vom Schwein, überbacken mit Käse, serviert mit Brot.',
    descEn: 'Pork ragout baked with cheese, served with bread.',
    price: '7,50€',
    category: 'vorspeisen',
  },
  {
    id: 'schweineschnitzel',
    imgDesktop: '/menu-media/schweineschnitzel-1024.webp',
    imgMobile: '/menu-media/schweineschnitzel-640.webp',
    video: '/menu-media/schweineschnitzel.webm',
    tagDe: 'Hauptgericht',
    tagEn: 'Main Course',
    nameDe: 'Saftiges Schweineschnitzel',
    nameEn: 'Juicy Pork Schnitzel',
    descDe: 'Serviert mit cremigen Pilzen und Pommes.',
    descEn: 'Served with creamy mushrooms and fries.',
    price: '16,50€',
    category: 'hauptgerichte',
  },
  {
    id: 'zigeuner-schnitzel',
    imgDesktop: '/menu-media/zigeuner-schnitzel-1024.webp',
    imgMobile: '/menu-media/zigeuner-schnitzel-640.webp',
    video: '/menu-media/zigeuner-schnitzel.webm',
    tagDe: 'Hauptgericht',
    tagEn: 'Main Course',
    nameDe: '"Zigeuner-Schnitzel"',
    nameEn: '"Zigeuner Schnitzel"',
    descDe: 'Serviert mit kräftiger Paprikagemüse-Sauce und Pommes.',
    descEn: 'Served with a bold pepper vegetable sauce and fries.',
    price: '16,50€',
    category: 'hauptgerichte',
  },
  {
    id: 'currywurst',
    imgDesktop: '/menu-media/currywurst-1024.webp',
    imgMobile: '/menu-media/currywurst-640.webp',
    video: '/menu-media/currywurst.webm',
    tagDe: 'Hauptgericht',
    tagEn: 'Main Course',
    nameDe: 'Currywurst',
    nameEn: 'Currywurst',
    descDe: 'Serviert mit hausgemachter Sauce und Pommes.',
    descEn: 'Served with homemade sauce and fries.',
    price: '15,50€',
    category: 'hauptgerichte',
  },
  {
    id: 'alt-nebraer-hacksteak',
    imgDesktop: '/menu-media/alt-nebraer-hacksteak-1024.webp',
    imgMobile: '/menu-media/alt-nebraer-hacksteak-640.webp',
    video: '/menu-media/alt-nebraer-hacksteak.webm',
    tagDe: 'Hauptgericht',
    tagEn: 'Main Course',
    nameDe: '"Alt-Nebraer-Hacksteak"',
    nameEn: '"Old Nebra Minced Steak"',
    descDe: 'Serviert mit Zwiebel-Biergemüse und Kartoffelstampf.',
    descEn: 'Served with onion beer vegetables and mashed potatoes.',
    price: '14,50€',
    category: 'hauptgerichte',
  },
  {
    id: 'pfannenschaschlik',
    imgDesktop: '/menu-media/pfannenschaschlik-1024.webp',
    imgMobile: '/menu-media/pfannenschaschlik-640.webp',
    video: '/menu-media/pfannenschaschlik.webm',
    tagDe: 'Hauptgericht',
    tagEn: 'Main Course',
    nameDe: 'Kräftiges Pfannenschaschlik',
    nameEn: 'Hearty Skillet Shashlik',
    descDe: 'Ragout vom Schweinenacken und Leber, verfeinert mit Gewürzgurke und Zwiebel, serviert mit Kartoffelstampf.',
    descEn: 'Pork neck and liver ragout refined with pickled cucumber and onion, served with mashed potatoes.',
    price: '11,50€',
    category: 'hauptgerichte',
  },
  {
    id: 'hamburger-art-schnitzel',
    imgDesktop: '/menu-media/hamburger-art-schnitzel-1024.webp',
    imgMobile: '/menu-media/hamburger-art-schnitzel-640.webp',
    video: '/menu-media/hamburger-art-schnitzel.webm',
    tagDe: 'Hauptgericht',
    tagEn: 'Main Course',
    nameDe: 'Schnitzel "Hamburger Art"',
    nameEn: 'Schnitzel "Hamburg Style"',
    descDe: 'Serviert mit Bratkartoffeln und Spiegelei.',
    descEn: 'Served with fried potatoes and a fried egg.',
    price: '17,50€',
    category: 'hauptgerichte',
  },
  {
    id: 'schuesselsuelze',
    imgDesktop: '/menu-media/schuesselsuelze-1024.webp',
    imgMobile: '/menu-media/schuesselsuelze-640.webp',
    video: '/menu-media/schuesselsuelze.webm',
    tagDe: 'Hauptgericht',
    tagEn: 'Main Course',
    nameDe: 'Schüsselsülze',
    nameEn: 'Jellied Pork Bowl',
    descDe: 'Serviert mit Bratkartoffeln und hausgemachter Remoulade.',
    descEn: 'Served with fried potatoes and homemade remoulade.',
    price: '13,50€',
    category: 'hauptgerichte',
  },
  {
    id: 'schnitzel-au-four',
    imgDesktop: '/menu-media/schnitzel-au-four-1024.webp',
    imgMobile: '/menu-media/schnitzel-au-four-640.webp',
    video: '/menu-media/schnitzel-au-four.webm',
    tagDe: 'Hauptgericht',
    tagEn: 'Main Course',
    nameDe: 'Schnitzel "au four"',
    nameEn: 'Schnitzel "au four"',
    descDe: 'Gratiniert mit Würzfleisch und Käse, serviert mit Pommes.',
    descEn: 'Gratinated with wuerzfleisch and cheese, served with fries.',
    price: '17,50€',
    category: 'hauptgerichte',
  },
  {
    id: 'bauernfruehstueck',
    imgDesktop: '/menu-media/bauernfruehstueck-1024.webp',
    imgMobile: '/menu-media/bauernfruehstueck-640.webp',
    video: '/menu-media/bauernfruehstueck.webm',
    tagDe: 'Klassiker',
    tagEn: 'Classic',
    nameDe: 'Bauernfrühstück',
    nameEn: "Farmer's Breakfast",
    descDe: 'Serviert mit Rohkostsalat und Gewürzgurke.',
    descEn: 'Served with fresh salad and pickled cucumber.',
    price: '12,50€',
    category: 'klassiker',
  },
  {
    id: 'strammer-max',
    imgDesktop: '/menu-media/strammer-max-1024.webp',
    imgMobile: '/menu-media/strammer-max-640.webp',
    video: '/menu-media/strammer-max.webm',
    tagDe: 'Klassiker',
    tagEn: 'Classic',
    nameDe: 'Strammer Max',
    nameEn: 'Strammer Max',
    descDe: 'Schwarzbrot mit Schinken, zwei Spiegeleiern, Rohkostsalat und Gewürzgurke.',
    descEn: 'Dark bread with ham, two fried eggs, fresh salad and pickled cucumber.',
    price: '9,50€',
    category: 'klassiker',
  },
  {
    id: 'backfisch',
    imgDesktop: '/menu-media/backfisch-1024.webp',
    imgMobile: '/menu-media/backfisch-640.webp',
    video: '/menu-media/backfisch.webm',
    tagDe: 'Klassiker',
    tagEn: 'Classic',
    nameDe: 'Backfisch',
    nameEn: 'Fried Fish',
    descDe: 'Serviert mit hausgemachter Remoulade und Bratkartoffeln.',
    descEn: 'Served with homemade remoulade and fried potatoes.',
    price: '13,50€',
    category: 'klassiker',
  },
  {
    id: 'geschnetzeltes',
    imgDesktop: '/menu-media/geschnetzeltes-1024.webp',
    imgMobile: '/menu-media/geschnetzeltes-640.webp',
    video: '/menu-media/geschnetzeltes.webm',
    tagDe: 'Pfanne & Burger',
    tagEn: 'Skillet & Burger',
    nameDe: 'Geschnetzeltes',
    nameEn: 'Sliced Chicken in Cream Sauce',
    descDe: 'Zarte Hähnchenbruststreifen mit cremigen Champignons, serviert mit Kroketten.',
    descEn: 'Tender chicken breast strips with creamy mushrooms, served with croquettes.',
    price: '18,50€',
    category: 'pfanne-burger',
  },
  {
    id: 'burger-st-georg',
    imgDesktop: '/menu-media/burger-st-georg-1024.webp',
    imgMobile: '/menu-media/burger-st-georg-640.webp',
    video: '/menu-media/burger-st-georg.webm',
    tagDe: 'Pfanne & Burger',
    tagEn: 'Skillet & Burger',
    nameDe: 'Burger "St. Georg"',
    nameEn: 'Burger "St. George"',
    descDe: 'Saftiger Rindfleisch-Burger mit Bacon, Spiegelei, Weißkrautsalat, BBQ-Sauce, Gewürzgurke und Schmorzwiebeln, serviert mit Pommes.',
    descEn: 'Juicy beef burger with bacon, fried egg, cabbage slaw, BBQ sauce, pickled cucumber and braised onions, served with fries.',
    price: '19,50€',
    category: 'pfanne-burger',
  },
  {
    id: 'nebraer-biersteak',
    imgDesktop: '/menu-media/nebraer-biersteak-1024.webp',
    imgMobile: '/menu-media/nebraer-biersteak-640.webp',
    video: '/menu-media/nebraer-biersteak.webm',
    tagDe: 'Steaks & Medaillons',
    tagEn: 'Steaks & Medallions',
    nameDe: 'Nebraer-Biersteak',
    nameEn: 'Nebra Beer Steak',
    descDe: 'Gebratenes Schweinenackensteak mit Schmorzwiebeln, mit Nebraer Bier abgelöscht und mit Bratkartoffeln serviert.',
    descEn: 'Roasted pork neck steak with braised onions, finished with Nebra beer and served with fried potatoes.',
    price: '18,50€',
    category: 'steaks-medaillons',
  },
  {
    id: 'schweinemedaillons',
    imgDesktop: '/menu-media/schweinemedaillons-1024.webp',
    imgMobile: '/menu-media/schweinemedaillons-640.webp',
    video: '/menu-media/schweinemedaillons.webm',
    tagDe: 'Steaks & Medaillons',
    tagEn: 'Steaks & Medallions',
    nameDe: 'Zarte Schweinemedaillons',
    nameEn: 'Tender Pork Medallions',
    descDe: 'Serviert mit cremigen Pilzen und Kroketten.',
    descEn: 'Served with creamy mushrooms and croquettes.',
    price: '19,50€',
    category: 'steaks-medaillons',
  },
  {
    id: 'zigeuner-steak',
    imgDesktop: '/menu-media/zigeuner-steak-1024.webp',
    imgMobile: '/menu-media/zigeuner-steak-640.webp',
    video: '/menu-media/zigeuner-steak.webm',
    tagDe: 'Steaks & Medaillons',
    tagEn: 'Steaks & Medallions',
    nameDe: '"Zigeuner-Steak"',
    nameEn: '"Zigeuner Steak"',
    descDe: 'Saftig gebratenes Schweinenackensteak mit kräftiger Paprikagemüse-Sauce und Pommes.',
    descEn: 'Juicy pork neck steak with bold pepper vegetable sauce and fries.',
    price: '18,50€',
    category: 'steaks-medaillons',
  },
  {
    id: 'bierbrett-neue-liebe',
    imgDesktop: '/menu-media/bierbrett-neue-liebe-1024.webp',
    imgMobile: '/menu-media/bierbrett-neue-liebe-640.webp',
    video: '/menu-media/bierbrett-neue-liebe.webm',
    tagDe: 'Zum Bier',
    tagEn: 'For Beer',
    nameDe: 'Bierbrett Neue Liebe',
    nameEn: 'Neue Liebe Beer Board',
    descDe: 'Kleine Auswahl aus Kaminwurst, Käsewürfeln, Gewürzgurken und kräftigem Landbrot.',
    descEn: 'A small selection of smoked sausage, cheese cubes, pickles and hearty country bread.',
    price: '12,90€',
    category: 'zum-bier',
  },
  {
    id: 'brezelknusper-obazda',
    imgDesktop: '/menu-media/brezelknusper-obazda-1024.webp',
    imgMobile: '/menu-media/brezelknusper-obazda-640.webp',
    video: '/menu-media/brezelknusper-obazda.webm',
    tagDe: 'Zum Bier',
    tagEn: 'For Beer',
    nameDe: 'Brezelknusper mit Obazda',
    nameEn: 'Pretzel Crisps with Obazda',
    descDe: 'Warme Laugenbissen mit cremigem Bierkäse-Dip und roten Zwiebeln.',
    descEn: 'Warm pretzel bites with creamy beer cheese dip and red onions.',
    price: '6,90€',
    category: 'zum-bier',
  },
  {
    id: 'paprika-kartoffelecken',
    imgDesktop: '/menu-media/paprika-kartoffelecken-1024.webp',
    imgMobile: '/menu-media/paprika-kartoffelecken-640.webp',
    video: '/menu-media/paprika-kartoffelecken.webm',
    tagDe: 'Zum Bier',
    tagEn: 'For Beer',
    nameDe: 'Paprika-Kartoffelecken',
    nameEn: 'Paprika Potato Wedges',
    descDe: 'Knusprige Kartoffelecken mit Rauchpaprika und milder Kräutercreme.',
    descEn: 'Crispy potato wedges with smoked paprika and mild herb cream.',
    price: '7,50€',
    category: 'zum-bier',
  },
  {
    id: 'nebraer-bier-st-georg',
    imgDesktop: '/menu-media/nebraer-bier-st-georg-1024.webp',
    imgMobile: '/menu-media/nebraer-bier-st-georg-640.webp',
    tagDe: 'Bier & Drinks',
    tagEn: 'Beer & Drinks',
    nameDe: '"Nebraer Bier" St. Georg',
    nameEn: '"Nebra Beer" St. George',
    descDe: 'Feinmilde Bierspezialität mit malzig-süßem, vollmundigem Geschmack. 0,5L.',
    descEn: 'A smooth beer specialty with malty-sweet, full-bodied flavor. 0.5L.',
    price: '4,50€',
    category: 'bier-drinks',
  },
  {
    id: 'koestritzer-schwarzbier',
    imgDesktop: '/kostritzer_desktop.webp',
    imgMobile: '/kostritzer_mobile.webp',
    tagDe: 'Bier & Drinks',
    tagEn: 'Beer & Drinks',
    nameDe: 'Köstritzer Schwarzbier',
    nameEn: 'Köstritzer Dark Beer',
    descDe: 'Herb-fein mit röstigen Malznoten und eleganter Tiefe. 0,5L.',
    descEn: 'Delicately bitter with roasted malt notes and elegant depth. 0.5L.',
    price: '4,80€',
    category: 'bier-drinks',
  },
  {
    id: 'keller-radler',
    imgDesktop: '/kostritzer_desktop.webp',
    imgMobile: '/kostritzer_mobile.webp',
    tagDe: 'Bier & Drinks',
    tagEn: 'Beer & Drinks',
    nameDe: 'Keller-Radler',
    nameEn: 'Cellar Radler',
    descDe: 'Erfrischend gemischt, leicht, spritzig und ideal zum Essen. 0,5L.',
    descEn: 'Refreshingly mixed, light, sparkling and ideal with food. 0.5L.',
    price: '4,60€',
    category: 'bier-drinks',
  },
  {
    id: 'hausgemachte-limonade',
    imgDesktop: '/kostritzer_desktop.webp',
    imgMobile: '/kostritzer_mobile.webp',
    tagDe: 'Bier & Drinks',
    tagEn: 'Beer & Drinks',
    nameDe: 'Hausgemachte Limonade',
    nameEn: 'Homemade Lemonade',
    descDe: 'Zitrone, Minze und kühler Sprudel mit frischer Note. 0,4L.',
    descEn: 'Lemon, mint and cool sparkling water with a fresh finish. 0.4L.',
    price: '4,90€',
    category: 'bier-drinks',
  },
]
